# Generated by Django 5.1.4 on 2024-12-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=50)),
                ("company_location", models.CharField(max_length=50)),
                ("company_about", models.TextField()),
                (
                    "company_type",
                    models.CharField(
                        choices=[("IT", "IT"), ("Non IT", "Non IT")], max_length=50
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.CharField(max_length=100)),
                ("employee_email", models.CharField(max_length=50)),
                ("employee_address", models.CharField(max_length=200)),
                ("employee_phone", models.CharField(max_length=10)),
                ("employee_about", models.TextField()),
                (
                    "employee_position",
                    models.CharField(
                        choices=[
                            ("Software Developer Engineer", "SDE"),
                            ("Data Scientiest", "DS"),
                            ("Project Manager", "PM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
